################################################
# Package Raccolta Differenziata - Ver. 1.2.0  #
# Autore: Saverio Gravagnola                   #
# Sito:   http://domoticamente.it              #
# Card by: Simonz82                            #
# sito: https://github.com/Simonz82/ha_garbage #
# modificata da Agostino Pitasi		       #
################################################

homeassistant:
  time_zone: Europe/Rome
  customize:
    package.node_anchors:
      customize: &customize
        package: "Raccolta Differenziata 1.2"
        author: "Saverio Gravagnola, Simonz82, Agostino Pitasi"
        reference: "WebSite: www.domoticamente.it, https://github.com/Simonz82/ha_garbage"

      ########################
      # IMPOSTAZIONI PACKAGE #
      ########################
      setting:
        Media Player Alexa: &alexa 
           - media_player.ovunque
        Media Player Google: &google
          - media_player.soggiorno
        Device per notifica push 1: &push1 mobile_app_redmi_note_9_pro
        Device per notifica push 2: &push2 mobile_app_mary_redmi
        Device per notifica push 3: &push3 entita_smartphone_3
        Device per notifica push 4: &push4 entita_smartphone_4
        Device per notifica push 5: &push5 entita_smartphone_5
        Rifiuto 1: &rifiuto1 "♻ Indifferenziato"
        Rifiuto 2: &rifiuto2 "🍌 Organico"
        Rifiuto 3: &rifiuto3 "🔪 Plastica e metalli"
        Rifiuto 4: &rifiuto4 "🥡 Carta e cartone"
        Rifiuto 5: &rifiuto5 "🥛 Vetro"
        Rifiuto 6: &rifiuto6 "🍌🥛 Organico e Vetro"
        Rifiuto 7: &rifiuto7 "🤷 Nulla" #non modificare

########################################################################################################################
#                                                     ATTENZIONE!                                                      #
#                  NON MODIFICARE AL DI SOTTO DI QUESTE RIGHE SE NON SI È SICURI DI QUELLO CHE SI FA.                  #
#                 I PARAMETRI DA CONFIGURARE PER IL CORRETTO FUNZIONAMENTO SONO SOLO QUELLI QUI SOPRA.                 #
########################################################################################################################

###########
# BOOLEAN #
###########
input_boolean:
  # RACCOLTA DIFFERENZIATA DA NOTIFICARE
  raccolta_differenziata_da_notificare:
    name: Raccolta differenziata da notificare
    icon: mdi:bell
    
 # ATTIVA SECONDA SETTIMANA
  raccolta_differenziata_seconda_settimana:
    name: Raccolta differenziata seconda settimana
    icon: mdi:calendar-range

##########
# NUMBER #
##########
input_number:
  # FREQUENZA NOTIFICHE
  frequenza_notifiche_raccolta_differenziata:
    name: Frequenza notifiche raccolta differenziata
    min: 5
    max: 60
    step: 5
    unit_of_measurement: "min"
    icon: mdi:timer-sync

############
# DATETIME #
############
input_datetime:
  # START NOTIFICHE
  raccolta_differenziata_notifiche_start_time:
    name: Inizio notifiche raccolta differenziata
    has_time: true
    has_date: false
    icon: mdi:timer-music
  # END NOTIFICHE
  raccolta_differenziata_notifiche_end_time:
    name: Fine notifiche raccolta differenziata
    has_time: true
    has_date: false
    icon: mdi:timer-off

##########
# SELECT #
##########
input_select:
  # GIORNI RACCOLTA DIFFERENZIATA
  raccolta_differenziata_lun:
    name: Rifiuto raccolto il lunedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_mar:
    name: Rifiuto raccolto il martedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_mer:
    name: Rifiuto raccolto il mercoledì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_gio:
    name: Rifiuto raccolto il giovedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_ven:
    name: Rifiuto raccolto il venerdì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_sab:
    name: Rifiuto raccolto il sabato
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_dom:
    name: Rifiuto raccolto domenica
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7

# GIORNI RACCOLTA DIFFERENZIATA 2 settimana
  raccolta_differenziata_lun2:
    name: Rifiuto raccolto il lunedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_mar2:
    name: Rifiuto raccolto il martedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_mer2:
    name: Rifiuto raccolto il mercoledì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_gio2:
    name: Rifiuto raccolto il giovedì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_ven2:
    name: Rifiuto raccolto il venerdì
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_sab2:
    name: Rifiuto raccolto il sabato
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7
  raccolta_differenziata_dom2:
    name: Rifiuto raccolto domenica
    icon: mdi:delete-empty
    options:
      - *rifiuto1
      - *rifiuto2
      - *rifiuto3
      - *rifiuto4
      - *rifiuto5
      - *rifiuto6
      - *rifiuto7     
###########
# SENSORI #
###########
sensor:
  - platform: template
    sensors:
      # GIORNO DELLA SETTIMANA
      giorno_della_settimana:
        friendly_name: "Giorno della settimana"
        value_template: >
          {{ ['lun','mar','mer','gio','ven','sab','dom'][now().weekday()] }}
        icon_template: >-
          mdi:{{['emoticon-dead-outline', 'emoticon-angry-outline', 'emoticon-sad-outline','emoticon-neutral-outline','emoticon-cool-outline','emoticon-excited-outline','emoticon-happy-outline'][now().weekday()] }}
      # NOME DELL'INPUT DEL GIORNO DELLA SETTIMANA
      input_giorno_settimana_rifiuti:
        value_template: >
          {{ "raccolta_differenziata_" + states.sensor.giorno_della_settimana.state}}


#RACCOLTA DIFFERENZIATA
# Prodotto da conferire in base al giorno
  - platform: template
    sensors:
       raccoltadifferenziata:
         entity_id: sensor.date
         friendly_name: "Orario di conferimento" 
         value_template: >-
           {% if (((now() - as_datetime(0)).days // 7) % 2 == 0) and (is_state('input_boolean.raccolta_differenziata_seconda_settimana', 'on'))  %}
           {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state+"2")[2:] }}
           {% else %}
            {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state)[2:] }}
           {% endif %}
          
# Giorno della settimana
  - platform: template
    sensors:
      giornosettimana:
         entity_id: sensor.date
         friendly_name: "Oggi è:"
         value_template: >-
           {% if now().weekday() == 0 -%}
             Lunedì
           {%- elif now().weekday() == 1 -%}
             Martedì
           {%- elif now().weekday() == 2 -%}
             Mercoledì
           {%- elif now().weekday() == 3 -%}
             Giovedì
           {%- elif now().weekday() == 4 -%}
             Venerdì
           {%- elif now().weekday() == 5 -%}
             Sabato
           {%- elif now().weekday() == 6 -%}
             Domenica
           {%- endif %}

# Giorno del ritiro
  - platform: template
    sensors:
       giornoritiro:
         entity_id: sensor.date
         friendly_name: "Giorno del ritiro:"
         value_template: >-
           {% if now().weekday() == 6 -%}
             Lunedì
           {%- elif now().weekday() == 0 -%}
             Martedì
           {%- elif now().weekday() == 1 -%}
             Mercoledì
           {%- elif now().weekday() == 2 -%}
             Giovedì
           {%- elif now().weekday() == 3 -%}
             Venerdì
           {%- elif now().weekday() == 4 -%}
             Sabato
           {%- elif now().weekday() == 5 -%}
             Domenica
           {%- endif %}

#FINE RACCOLTA DIFFERENZIATA  
####################
# NOTIFICHE GRUPPO #
####################
notify:
  - name: Raccolta Differenziata Gruppo Notifiche App
    platform: group
    services:
      - service: *push1
      - service: *push2
      - service: *push3
      - service: *push4
      - service: *push5

###############
# AUTOMAZIONI #
###############
automation:
  # ATTIVA DA NOTIFICARE QUANDO ORARIO DI INIZIO NOTIFICHE
  - alias: Attiva da notificare raccolta differenziata
    id: Attiva da notificare raccolta differenziata
    mode: single
    trigger:
      - platform: time
        at: "04:59:00"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.raccolta_differenziata_da_notificare
  # DISATTIVA DA NOTIFICARE QUANDO ORARIO DI FINE NOTIFICHE
  - alias: Disattiva da notificare raccolta differenziata
    id: Disattiva da notificare raccolta differenziata
    mode: single
    trigger:
      - platform: time
        at: input_datetime.raccolta_differenziata_notifiche_end_time
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.raccolta_differenziata_da_notificare
  # RICORDA RACCOLTA DIFFERENZIATA
  - alias: Ricorda raccolta differenziata
    id: Ricorda raccolta differenziata
    mode: single
    trigger:
      - platform: template
        value_template: "{{ (now().minute % states('input_number.frequenza_notifiche_raccolta_differenziata')|int(2) == 0) and (states('input_select.raccolta_differenziata_' + states.sensor.giorno_della_settimana.state)[2:] != 'Nulla') }}"
    condition:
      - condition: state
        entity_id: input_boolean.raccolta_differenziata_da_notificare
        state: "on"
      - condition: time
        after: input_datetime.raccolta_differenziata_notifiche_start_time
        before: input_datetime.raccolta_differenziata_notifiche_end_time
    action:
      - service: notify.raccolta_differenziata_gruppo_notifiche_app
        continue_on_error: true
        data:
          title: 🚮 Ricordati di buttare l'immondizia
          message: >-
            {% if (((now() - as_datetime(0)).days // 7) % 2 == 0) and (is_state('input_boolean.raccolta_differenziata_seconda_settimana', 'on'))  %}
            {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state+"2") }}
            {% else %}
             {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state) }}
             {% endif %}
      - service: notify.alexa_media
        continue_on_error: true
        data:
          target:
            - *alexa
          data:
            type: announce
            method: spoken
          message: >-
             {% if (((now() - as_datetime(0)).days // 7) % 2 == 0) and (is_state('input_boolean.raccolta_differenziata_seconda_settimana', 'on'))  %}
             Ricordati di buttare l'immondizia. Oggi si butta {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state+"2")[2:] }}
             {% else %}
             Ricordati di buttare l'immondizia. Oggi si butta {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state)[2:] }}
              {% endif %}
      - service: tts.google_translate_say
        continue_on_error: true
        data:
            entity_id: *google
            message: >-
              {% if (((now() - as_datetime(0)).days // 7) % 2 == 0) and (is_state('input_boolean.raccolta_differenziata_seconda_settimana', 'on'))  %}
              Ricordati di buttare l'immondizia. Oggi si butta {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state+"2")[2:] }}  
              {% else %}
               Ricordati di buttare l'immondizia. Oggi si butta {{ states("input_select.raccolta_differenziata_" + states.sensor.giorno_della_settimana.state")[2:] }}  
              {% endif %}